# Generated by Django 4.2.6 on 2023-11-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_available',
            field=models.BooleanField(default=False),
        ),
    ]
